apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logto.secretName" . }}
  labels:
    {{- include "logto.labels" . | nindent 4 }}
type: Opaque
data:
  TRUST_PROXY_HEADER: {{ .Values.trustProxyHeader | b64enc | quote }}
  {{- if .Values.postgresql.enabled }}
  DB_URL: {{ "postgresql://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DATABASE)" | b64enc | quote }}
  POSTGRES_HOST: {{ printf "%s.%s.svc.cluster.local" (include "postgresql.v1.primary.fullname" .Subcharts.postgresql) .Release.Namespace | b64enc | quote }}
  POSTGRES_PORT: {{ include "postgresql.v1.service.port" .Subcharts.postgresql | b64enc | quote }}
  POSTGRES_USERNAME: {{ include "postgresql.v1.username" .Subcharts.postgresql | b64enc | quote }}
  {{- else }}
  DB_URL: {{ .Values.dbUrl | b64enc | quote }}
  {{- end }}